Scheduler_MVC/Scheduler_MVC/Models/appointments.cs
namespace Scheduler_MVC.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public  partial class appointments
    {

        public int appt_client_id { get; set; }

        public int customer_id { get; set; }

        [Key]
        public int appt_id { get; set; }

        public DateTime appt_date_time { get; set; }

        [StringLength(200)]
        public string recording_uri { get; set; }

        public DateTime time_stamp { get; set; }

        [Required]
        [StringLength(20)]
        public string appt_status { get; set; }

        [Required]
        [StringLength(5)]
        public string appt_type { get; set; }

        public int? appt_cm_id { get; set; }

        [Required]
        [StringLength(50)]
        public string appt_zone { get; set; }

        [StringLength(20)]
        public string agent_name { get; set; }

        [StringLength(1000)]
        public string notes { get; set; }

        public bool? h2 { get; set; }

        public int? old_appt_id { get; set; }

        public bool? released { get; set; }

        [StringLength(50)]
        public string appt_result { get; set; }

        public DateTime? appt_result_datetime { get; set; }

        public DateTime? appt_update_status_date { get; set; }

        public int? OldCustomerID { get; set; }

        [NotMapped]
        public int zipcode { get; set; }

        [ForeignKey("appt_client_id")]
        public virtual valid_clients Client { get; set; }

        [NotMapped]
        public bool Empty
        {
            get
            {
                return (appt_id >1);
            }
        }

        //[ForeignKey("appt_client_id")]
        //public virtual zones Zone { get; set;}


    }
}

Scheduler_MVC/Scheduler_MVC/Models/cmschedule.cs
namespace Scheduler_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class cmschedule : DbContext
    {
        public cmschedule()
            : base("name=communityMeetingConn")
        {
        }

        public virtual DbSet<community_meeting_schedule> community_meeting_schedule { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<community_meeting_schedule>()
                .Property(e => e.state)
                .IsFixedLength();
        }
    }
}

Scheduler_MVC/Scheduler_MVC/Controllers/appointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Scheduler_MVC.Models;
using System.Data.SqlClient;
using Microsoft.Ajax.Utilities;
using Scheduler_MVC.Controllers;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Reflection;


//System.Web.Mvc Copy Local = True
//System.Web.Abstractions Copy Local = True
//System.Web.Routing Copy Local = True
namespace Scheduler_MVC.Controllers
{
    //This is just a test comment to see if it gets committed to the scheduler_mvc branch in thr git repository
    public class appointmentsController : Controller
    {
        private appointmentContext db = new appointmentContext();

        // GET: appointments
        public ActionResult Index()
        {
            Console.WriteLine("fgjbdfgbhd");
            return View(db.appointments.ToList());
        }

        // Method with Tasks for Preprocess Appointments
        public async Task PreprocessAppointment()
        {
            var task_1 = GetApptTask();
            var task_2 = GetZoneTask();
            await Task.WhenAll(task_1, task_2);

            /*var query = task_1.Join(task_2,
                        t1 => t1.appt_client_id,
                        t2 => int.Parse(t2.zone_client_id),
                        (t1, t2) =>
                        new { t1, t2 }

               ).Where(o => o.t2.zip == "60827");*/
           
        }

        public async Task<IEnumerable<appointments>> GetApptTask(){
            using (var db = new appointmentContext())
            {

                var result = db.appointments.Where(d => d.appt_client_id == 15 && d.customer_id == 68009);
                //eturn Task.Run(()=>result);
                return await result.ToListAsync();
            }


        }

        public async Task <IEnumerable<zones>> GetZoneTask()
        {
            //var result = db.zones.Where(d => d.zone_client_id == "15").AsEnumerable().Distinct<zones>(new zones.Comparer());
            //return await result.ToListAsync();
            using (var db = new appointmentContext())
            {
                var allZones = db.zones.Where(d => d.zone_client_id == "15").ToList();
                var az = await db.zones.Where(d => d.zone_client_id == "15").ToListAsync<zones>().ConfigureAwait(false);
                return az.Distinct<zones>(new zones.Comparer()).ToList();
            }
        }


        // This method picks all the slots which should be excluded based on the given date and the given zone (which is retreived from the join of appointments and zones) appointments slots need to be excluded
        public void ApptEcxlusions(int id)
        {
            DateTime dt1 = new DateTime(2006,11,23,7,0,0);
            DateTime chkDate = new DateTime(2006,11,23,13,0,0);
            DateTime dt2 = new DateTime(2006, 11, 24, 20, 0, 0);
            IEnumerable<appointment_exclusions> result = db.appt_ecxlusions.Where(d=> d.appt_excl_client_id==id && System.Data.Entity.SqlServer.SqlFunctions.DateDiff("hour",d.appt_start_date_time,chkDate)>0 &&
            System.Data.Entity.SqlServer.SqlFunctions.DateDiff("hour", chkDate,d.appt_end_date_time) > 0);
            

        }

        // This method will pick the number of duplicate slots on a given date and time 
        public void AppointmentCheck() {
            DateTime dt = new DateTime(2015, 10, 16, 9, 0, 0);
            int clientid = 51;
            int customer_id = 2180;
            IEnumerable<appointments> result = db.appointments.Where(d => d.appt_client_id == clientid && d.customer_id == customer_id && System.Data.Entity.SqlServer.SqlFunctions.DateDiff("hour", dt, d.appt_date_time) == 0);
            var cnt = db.appointments.Where(d => d.appt_client_id == clientid && d.customer_id == customer_id && System.Data.Entity.SqlServer.SqlFunctions.DateDiff("hour", dt, d.appt_date_time) == 0).ToList().Count();


        }
       
        //This method joins the zones and the appointments and results can be extracted from that 
        public void PreProcessAppointments(IEnumerable<appointments>draft)
        {
            /* System.Data.Entity.Core.Objects.ObjectContext obj= ((System.Data.Entity.Infrastructure.IObjectContextAdapter)db).ObjectContext;
             var connection = obj.Connection as System.Data.Entity.Core.EntityClient.EntityConnection;
             System.Data.Entity.Core.EntityClient.EntityCommand command = connection.CreateCommand();

             command.CommandText = "Select value P  from zones as P where P.zone_client_id="+"51";
             connection.Open();
             System.Data.Entity.Core.EntityClient.EntityDataReader reader = command.ExecuteReader(CommandBehavior.SequentialAccess);*/


            var mytask = PreprocessAppointment();
            Task.Run(async () => { await PreprocessAppointment(); }).Wait();

            draft = db.appointments.Where(d => d.appt_client_id == 15 && d.customer_id == 68009);
            IEnumerable<zones> result = db.zones.Where(d => d.zone_client_id == "15").AsEnumerable().Distinct<zones>(new zones.Comparer());
            var query = draft.Join(result,
                         t1=> t1.appt_client_id,
                         t2 => int.Parse(t2.zone_client_id),
                         (t1,t2)=>
                         new {t1,t2}

                ).Where(o=>o.t2.zip=="60827");

            IEnumerable<Tuple< string,int,string>> query1 = draft.Join(result,
                         t1 => t1.appt_client_id,
                         t2 => int.Parse(t2.zone_client_id),
                         (t1, t2) =>
                         new { t1, t2 }

                ).Where(o => o.t2.zip == "60827").Select(c=> new Tuple<string,int,string>(c.t1.agent_name,c.t1.appt_client_id,c.t2.zip)).ToList();


            DataTable MyDataTable = DT.ToDataTable(query1);

            foreach (var obj in query1)
            {

                System.Diagnostics.Debug.WriteLine(
                    "{0} - {1} - {2}",
                    obj.Item1.ToString(),
                    obj.Item2.ToString(),
                    obj.Item3.ToString());
                    

            }
           /*foreach (var obj in query)
            {
                
                System.Diagnostics.Debug.WriteLine(
                    "{0} - {1} - {2} - {3}",
                    obj.t1.Client.client_id.ToString(),
                    obj.t1.appt_zone,
                    obj.t1.appt_date_time,
                    obj.t2.zip);
            }*/
            
            
            System.Diagnostics.Debug.WriteLine(query);
            //IEnumerable<zones> result1 =  db.zones.Select(e => new { e.zip, e.zone, e.zone_client_id }).Where(u => u.zone_client_id=="15").Distinct(new zones.Comparer());


            //List<zones> zones=result.ToList();
            //return View("View",result.ToList());


        }

        // GET: appointments/Details/?clientid=51&custid=15287
        public ActionResult Details(int clientid,int custid)

        {
            if (clientid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            //Commented insertAppointments() . Its a working code. Can be included later

            //insertAppointments();
            ApptEcxlusions(15);

            AppointmentCheck();
            IEnumerable <appointments> draft = db.appointments.Where(d => d.appt_client_id == clientid && d.customer_id == custid);
            PreProcessAppointments(draft);
            foreach (appointments s in draft)
            {
                System.Diagnostics.Debug.WriteLine(" I am the client information here in the function. Displayed for test"+" " +s.Client.client_id + " " + s.Client.inbound_hv);
            }

            /*appointment appointment = db.appointments.Find(clientid);
            if (appointment == null)
            {
                return HttpNotFound();
            }*/

            /*if (draft == null)
                return View("Create");*/

            return View(draft.ToList());
        }

        // GET: appointments/Create
        public ActionResult Create()
        {
            System.Diagnostics.Debug.WriteLine("I am a commnet in Create action method");
            return View();
        }

        // POST: appointments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /* [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Create([Bind(Include = "appt_id,appt_client_id,customer_id,appt_date_time,recording_uri,time_stamp,appt_status,appt_type,appt_cm_id,appt_zone,agent_name,notes,h2,old_appt_id,released,appt_result,appt_result_datetime,appt_update_status_date,OldCustomerID")] appointments appointment)
         {
             if (ModelState.IsValid)
             {
                 db.appointments.Add(appointment);
                 db.SaveChanges();
                 return RedirectToAction("Index");
             }

             return View(appointment);
         }*/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( appointments appointment)
        {

            IEnumerable<appointments>draft = db.appointments.Where(d => d.appt_client_id == appointment.appt_client_id && d.customer_id == appointment.customer_id);
            IEnumerable<zones> result = db.zones.Where(d => d.zone_client_id == appointment.appt_client_id.ToString() && d.zip == appointment.zipcode.ToString()).AsEnumerable().Distinct<zones>(new zones.Comparer());
            /*IEnumerable<Tuple<string>> query1 = draft.Join(result,
                       t1 => t1.appt_client_id,
                       t2 => int.Parse(t2.zone_client_id),

Scheduler_MVC/Scheduler_MVC/Views/appointments/CMSConfim.cshtml
@*@model  IEnumerable<Scheduler_MVC.Models.community_meeting_schedule>*@
@model  Scheduler_MVC.Models.cmsViewModel

@{
    ViewBag.Title = "Details";
}

@*<h2>Details</h2>*@

<div style="background-color:lavender">
@using (Html.BeginForm("CMSConfim", "appointments", FormMethod.Post))

{
    <h4 align="center">Scheduled appointment</h4>
    <hr />

    @Html.HiddenFor(model => model.appt_id, new { id = "appt_id" })
    @Html.HiddenFor(model => model.appt_client_id, new { id = "appt_client_id" })
    @Html.HiddenFor(model => model.appt_date_time)
    @Html.HiddenFor(model => model.appt_status)
    @Html.HiddenFor(model => model.appt_type)
    @Html.HiddenFor(model => model.agent_name)
    @Html.HiddenFor(model => model.appt_cm_id)
    @Html.HiddenFor(model => model.appt_zone)
   
    <table class="table" style="border:black ">
        <tr>
            <th>
                CM ID 
            </th>
           
            <th>
                Appointment Time
            </th>
           
            <th>
                Location
            </th>
            <th>
                Address
            </th>
            
        </tr>
        

            @foreach (var item in Model.lst)
            {
                
                <tr>
                    <td>
                        
                        @Html.DisplayFor(model => item.cm_id)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.date_time)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.location)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.address)
                    </td>
                 </tr>
                
            }
         @for (var i = 0; i < Model.lst.Count; i++)
         {
                @Html.HiddenFor(m => m.lst[i].cm_id)
                @Html.HiddenFor(m => m.lst[i].address)
                @Html.HiddenFor(m => m.lst[i].cm_client_id)
                @Html.HiddenFor(m => m.lst[i].capacity)
                @Html.HiddenFor(m => m.lst[i].city)
                @Html.HiddenFor(m => m.lst[i].date_time)
                @Html.HiddenFor(m => m.lst[i].cancelled)
                @Html.HiddenFor(m => m.lst[i].location)
                @Html.HiddenFor(m => m.lst[i].state)
                @Html.HiddenFor(m => m.lst[i].zone)
         }





    </table>
    <div style="text-align:center;">
        <input type="submit" value="Back" id="backBtn" class="btn btn-default" />
        <input type="button" value="Submit" id="submitBtn" class="btn btn-default" style="display:inline-block;" />
    </div>

}
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
<script>
    console.log(@Model.lst);
    console.log("@Model.appt_status");
</script>
}

Scheduler_MVC/Scheduler_MVC/Views/appointments/CMSchedule.cshtml
@using Scheduler_MVC.Models
@model Scheduler_MVC.Models.appointments

@{
    ViewBag.Title = "CMSchedule";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Edit Appointment</h2>

<div style="width: 100%;  background-color: lavender; margin: 0 auto;align-content: center">
    @using (Html.BeginForm("CMSchedule", "appointments", FormMethod.Post, new { id = "appt_form" }))

    {

        @Html.AntiForgeryToken()
        <h4 align="center">CMS Appointment</h4>
        <div class="form-horizontal" style="margin-left: 30%">

            <hr />
            @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
            @Html.HiddenFor(model => model.appt_id, new { id = "appt_id" })
            @Html.HiddenFor(model => model.appt_client_id, new { id = "appt_client_id" })
            @* Adding the hidden fields to send client information along with the form*@
            @*@Html.HiddenFor(model => model.Client.client_name)
            @Html.HiddenFor(model => model.Client.AmcatDatabaseName)
            @Html.HiddenFor(model => model.appt_zone)*@
            <input name="rows" type="hidden" id="tbldata"/>





            <div class="form-group input-group-sm">
                @Html.LabelFor(model => model.appt_date_time, "Appointment Date", htmlAttributes: new { @class = "control-label col-md-2", style = "white-space: nowrap" })
                <div class="col-md-10">


                    @Html.EditorFor(model => model.appt_date_time, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                    <div id="timeSlots"></div>
                    @*This will be removed just for testing*@
                    @Html.EditorFor(model => model.appt_date_time, new { htmlAttributes = new { @class = "form-control", id = "postid" } })
                    @* @Html.TextBoxFor(model => model.appt_date_time, new { data_format ='dd/MM/yyyy HH:mm:ss PP' });*@



                    @Html.ValidationMessageFor(model => model.appt_date_time, "", htmlAttributes: new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.appt_status, "Appointment Status", htmlAttributes: new { @class = "control-label col-md-2", style = "white-space: nowrap" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.appt_status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.appt_status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.appt_type, "Appointment Type", htmlAttributes: new { @class = "control-label col-md-2", style = "white-space: nowrap" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.appt_type, new { htmlAttributes = new { @class = "form-control", id = "appttype" } })
                    @Html.ValidationMessageFor(model => model.appt_type, "", new { @class = "text-danger" })
                </div>
            </div>

           
                <table class="table table-striped table-hover table-bordered" style="margin-right:auto;margin-bottom:20px;width:70%;border:solid 1px;" id="tbl">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="chooseAll" id="chooseAll" /></th>
                            <th class="center">CMID</th>
                            <th class="center">CMDateTime</th>
                            <th class="center">CMLocation</th>
                            <th class="center">CMAddress</th>
                            <th class="center">CMCity</th>
                            <th class="center">CMState</th>
                            <th class="center">CMCapacity</th>
                            <th class="center">CMZone</th>
                            
                        </tr>
                    </thead>

                    <tbody id="cmsdata"></tbody>
                </table>
           

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @* Changing the id of submit button from subClick to subClick1 to prevent deferred post of the form *@
                    <input type="submit" value="Save" id="subClick1" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    @**@
    <div style="width: 100%;margin-left: 30%">
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/moment.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="~/Scripts/Trie.js"></script>
    <script type="text/javascript" src="~/Scripts/parseJsonObject.js"></script>
    <script>

        console.log("@Model.appt_type");
        console.log("@Model.appt_date_time");
        console.log("@Model.time_stamp");
        console.log("@Model.appt_client_id");
        console.log("@Model.customer_id");
        console.log("@Model.notes");



        function tableToJSON()
        {
            var myRows = [];
            var $headers = $("#tbl th");
            var $rows = $("#tbl tbody tr").each(function(index) {
                $cells = $(this).find("td");
                myRows[index] = {};
                $cells.each(function(cellIndex) {
                    myRows[index][$($headers[cellIndex]).html()] = $(this).html();
                });
            });
            var myObj = {};
            myObj.myrows = myRows;
            //alert(JSON.stringify(myRows));
            var rows = [];
            var rowChecked = [];
            $('#tbl tbody tr').each(function(i, n){
                var $row = $(n);
                rows.push({
                    id: $row.find('td:eq(0) input[type=checkbox]').prop('checked'),
                    cm_id: $row.find('td:eq(1)').text(),
                    date_time: $row.find('td:eq(2)').text(),
                    location:$row.find('td:eq(3)').text(),
                    address: $row.find('td:eq(4)').text(),

                });
            });
           // alert(JSON.stringify(rows));
            console.log("rows[0]"+JSON.stringify(rows)[0]);
            console.log("rows[1]"+JSON.stringify(rows)[1]);
            for(var i =0;i<rows.length;i++)
            {
                if(rows[i]["id"]==true)
                {
                    console.log(JSON.stringify(rows[i]));
                    rowChecked.push(rows[i]);
                }


            }
            //alert(JSON.stringify(rowChecked));

            //setting the valule of the attribute for tbldata
            document.getElementById("tbldata").setAttribute("value",JSON.stringify(rowChecked));
            console.log("The json rows format is"+document.getElementById("tbldata").value);
        }

        $(function () {
            var dateAsObject;

            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };

            jQuery('.bootstrap-datetimepicker-widget').attr({ keepOpen: true });
            jQuery('.bootstrap-datetimepicker-widget').datetimepicker('show');
            jQuery('.datetimepicker').datetimepicker({ format: 'MM/DD/YYYY', inline: true, sideBySide: true, keepOpen: true, debug: true });
            //$('div.ui-datetimepicker').css({fontSize : '10px'});
            jQuery('.bootstrap-datetimepicker-widget').css({
                'display': 'inline-block',
                'width': '40%'
            });

            jQuery('.datetimepicker')
                .on("dp.change dp.show dp.hide",
                    function(e) {

                        jQuery('.bootstrap-datetimepicker-widget').css({
                            'display':'inline-block',
                            'width':'40%'
                        });
                        dateAsObject = moment(e.date).format("YYYY-MM-D");
                        /* console.log("moment format:" +
                             moment(new Date("Mon Jun 27 2016 00:00:00 GMT-0400"))
                             .format("YYYY-MM-DD HH:mm Z"));*/

                        //alert(dateAsObject);
                       // alert(e.date);
                       // alert(e.date.toString().substring(0, 3));
                        var str = e.date.toString().substring(0, 3);
                        var weekDays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
                        var T = new Trie();
                        var i;

                        for (i = 0; i < weekDays.length; i++) {
                            T.insert(weekDays[i]);
                        }
                        var day = T.autoComplete(e.date.toString().substring(0, 3))[0];
                        console.log(day[0]);
                        console.log(JSON.stringify({ 'day': day, 'id': @Model.appt_client_id,'date':moment(e.date).format("YYYY-MM-D") }));
                        $('#cmsdata').empty();

                        $.ajax({
                            @*original was Action("GetCms", "appointments")',*@
                            url: '@Url.Action("GetCms_", "appointments")',

                            type: 'POST',
                              @*data: JSON.stringify({ 'day': day, 'id': @Model.appt_client_id }),*@
                            data: JSON.stringify({ 'day': day, 'id': @Model.appt_client_id,'date':moment(e.date).format("YYYY-MM-D") }),
                            dataType: 'json',
                            processdata: false,
                            contentType: 'application/json; charset=utf-8',
                            success: function(data) {
                                //alert(JSON.stringify(data));
                                var pObj = new parseObject(JSON.stringify(data), "Text");
                                var lst = pObj.parse();
                                //console.log("parse.obj" + pObj.parse());
                                var row = "";
                                $.each(data, function(index, item){
                                    row+="<tr><td><input type='checkbox'id='"+item.CMID+"'/></td><td>"+item.CMID+"</td><td>"+item.CMDateTime+"</td><td>"+item.CMLocation+"</td><td>"+item.CMAddress+"</td><td>"+item.CMCity+"</td><td>"+item.CMState+"</td><td>"+item.CMCapacity+"</td><td>"+item.CMZone+"</td></tr>";
                                });
                                $("#cmsdata").html(row);
                                tableToJSON();
                                //alert(table);
                                //alert("another alert" + lst.split(","));
                            },
                            error: function(xhr, ajaxOptions, thrownError) {
                                alert("error");
                            },
                            complete: function(x, y) {
                                alert("complete");
                            }
                        });
                    });




            $('#subClick1').click(function(e){
                tableToJSON();
            });




            $("#subClick").click(function(event) {
                console.log("In form submit");
                event.preventDefault();

                var rows = [];
                $('#tbl tbody tr').each(function(i, n){
                    var $row = $(n);
                    rows.push({
                        id: $row.find('td:eq(0) input[type=checkbox]').prop('checked'),
                        cm_id: $row.find('td:eq(1)').text(),
                        date_time: $row.find('td:eq(2)').text(),
                        location:$row.find('td:eq(3)').text(),
                        address: $row.find('td:eq(4)').text(),

                    });
                });
                //alert(JSON.stringify(rows));

                $.ajax({
                    url: '@Url.Action("CMSchedule","appointments")',
                    type: 'POST',
                    data: JSON.stringify(rows),
                    async:false,
                    contentType: 'application/json; charset=utf-8',
                    success: function (result) {
                        //alert("success");
                        //$("#appt_form")[0].submit();
                    },
                    error: function (request) {
                        alert("error");
                    }
                });

            });

        });

    </script>

}

Scheduler_MVC/Scheduler_MVC/Views/appointments/Confirm.cshtml
@model  Scheduler_MVC.Models.appointments

@{
    ViewBag.Title = "Details";
}

@*<h2>Details</h2>*@

<div>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "confirm_form" }))
{
    <h4 align="center">Confirm appointment</h4>
    <hr />
    <table class="table" style="border:black ">
        <tr>
            <td>@Html.LabelFor(model => model.appt_date_time, "Appointment Date", htmlAttributes: new { @class = "control-label col-md-2", style = "display: inline;white-space: nowrap" })</td>
            <td>@Html.DisplayFor(model => model.appt_date_time)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.h2, "H2", htmlAttributes: new { @class = "control-label col-md-2" })</td>
            <td>@Html.DisplayFor(model => model.h2)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.notes, "Notes", htmlAttributes: new { @class = "control-label col-md-2" })</td>
            <td>@Html.DisplayFor(model => model.notes)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.appt_type, "Appointment Type", htmlAttributes: new { @class = "control-label col-md-2" })</td>
            <td>@Html.DisplayFor(model => model.appt_type)</td>
        </tr>
        <tr>
            <td><input type="submit" value="Back" id="backBtn" class="btn btn-default" /></td>
            <td><input type="button" value="Submit" id="submitBtn" class="btn btn-default" /></td>
        </tr>
            
    </table>
}
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $('#backBtn').click(function (e) {
            var model = @Html.Raw(Json.Encode(Model));
            console.log(model);
      });
    </script>
}

Scheduler_MVC/Scheduler_MVC/Views/appointments/View.cshtml
@model IEnumerable<Scheduler_MVC.Models.zones>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>zones</h4>
    <hr />
    <dl class="dl-horizontal">
        @foreach (var item in Model)
        {
       

        <dd>
            @Html.DisplayFor(model => item.zip)
        </dd>

       

        <dd>
            @Html.DisplayFor(model => item.zone)
        </dd>
        }
    </dl>

</div>